# Generated by Django 2.2.4 on 2019-08-12 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PortFolio_Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Language',
            new_name='language',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FilePathField(default=django.utils.timezone.now, path='/img'),
            preserve_default=False,
        ),
    ]
