# Generated by Django 2.2.4 on 2019-08-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortFolio_Project', '0003_auto_20190812_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/img'),
        ),
    ]
